# Generated by Django 4.2 on 2023-05-14 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=4)),
                ('zip_code', models.CharField(max_length=8)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=4)),
                ('cpf', models.CharField(max_length=11)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.date(2023, 5, 14))),
                ('my_issue', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issues.address')),
                ('sendBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.users')),
            ],
        ),
    ]
