# Generated by Django 4.2 on 2023-05-15 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='sendBy',
            new_name='send_by',
        ),
        migrations.AlterField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 5, 15)),
        ),
    ]
