# Generated by Django 4.2 on 2023-05-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_sendby_issues_send_by_alter_issues_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
